# .github/workflows/self-hosted-deploy.yml
name: Build and Deploy on Self-Hosted Runner

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted  # This is the key change!
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn clean compile assembly:single
    
    - name: Create application directory
      run: |
        sudo mkdir -p /opt/hello-world-java
        sudo chown $USER:$USER /opt/hello-world-java
    
    - name: Deploy application
      run: |
        # Copy built jar to deployment location
        cp target/hello-world-1.0.0-jar-with-dependencies.jar /opt/hello-world-java/
        
        # Create run script
        cat > /opt/hello-world-java/run.sh << 'EOF'
        #!/bin/bash
        cd $(dirname "$0")
        java -jar hello-world-1.0.0-jar-with-dependencies.jar
        EOF
        
        chmod +x /opt/hello-world-java/run.sh
    
    - name: Stop previous instance
      run: |
        pkill -f "java.*hello-world" || true
        sleep 2
    
    - name: Start application
      run: |
        cd /opt/hello-world-java
        nohup ./run.sh > app.log 2>&1 &
        sleep 3
        
        # Verify application is running
        if pgrep -f "java.*hello-world" > /dev/null; then
            echo "Application deployed successfully!"
            echo "Log output:"
            tail -n 5 app.log
        else
            echo "Application failed to start!"
            echo "Checking logs:"
            cat app.log
            exit 1
        fi
    
    - name: Show application status
      run: |
        echo "Current Java processes:"
        ps aux | grep -i java | grep -v grep || echo "No Java processes found"
        
        echo "Application directory contents:"
        ls -la /opt/hello-world-java/