name: Build and Deploy main

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      version:
        description: 'Version to deploy (optional)'
        required: false
        type: string

env:
  DEPLOYMENT_DIR: ~/apps/helloworld

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.set-artifact.outputs.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app-${{ github.run_id }}
          path: target/*.jar

      - name: Set artifact name output
        id: set-artifact
        run: echo "name=java-app-${{ github.run_id }}" >> $GITHUB_OUTPUT

  call-staging-deploy:
    needs: build
    if: github.event.inputs.environment == 'staging'
    uses: ./.github/workflows/deploy-staging.yml
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      deployment-dir: ${{ env.DEPLOYMENT_DIR }}
    secrets: inherit

  call-production-deploy:
    needs: build
    if: github.event.inputs.environment == 'production'
    uses: ./.github/workflows/deploy-production.yml
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      deployment-dir: ${{ env.DEPLOYMENT_DIR }}
      version: ${{ github.event.inputs.version }}
    secrets: inherit

  deployment-summary:
    runs-on: ubuntu-latest
    needs: 
      - call-staging-deploy
      - call-production-deploy
    if: always()
    
    steps:
      - name: Summary
        run: |
          echo "Deployment completed for environment: ${{ github.event.inputs.environment }}"
          echo "Build ID: ${{ github.run_id }}"
          echo "Version: ${{ github.event.inputs.version || 'latest' }}"